stages:
- name: Build and Publish to ACR
  steps:
  - publishImageConfig:
      dockerfilePath: apis/poi/web/Dockerfile
      buildContext: .
      tag: apis
      pushRemote: true
      registry: cthybridcloudacr.azurecr.io
  - publishImageConfig:
      dockerfilePath: apis/trips/Dockerfile
      buildContext: .
      tag: trips
      pushRemote: true
      registry: cthybridcloudacr.azurecr.io
  - publishImageConfig:
      dockerfilePath: apis/user-java/Dockerfile
      buildContext: .
      tag: userjava
      pushRemote: true
      registry: cthybridcloudacr.azurecr.io
  - publishImageConfig:
      dockerfilePath: apis/userprofile/Dockerfile
      buildContext: .
      tag: userprofile
      pushRemote: true
      registry: cthybridcloudacr.azurecr.io
timeout: 60
notification: {}
